const translations = {
    fr: {
        // Nav
        "nav.home": "Accueil",
        "nav.projects": "Projets",
        "nav.about": "À propos",
        "nav.contact": "Contact",

        // Home
        "home.eyebrow": "Gameplay & Systems",
        "home.title": "Créer des expériences jouables fiables et lisibles.",
        "home.lead": "Développeur de jeu vidéo, j’utilise Unreal Engine pour pouvoir mettre mes idées de jeux en vie. J'aime les grands projets et en apprendre plus dans ce monde vaste qu'est le GameDev.",
        "home.btn.projects": "Voir mes projets",
        "home.btn.about": "En savoir plus sur moi",
        "home.loc.label": "Localisation",
        "home.loc.value": "Chicoutimi (QC)",
        "home.disp.label": "Disponibilité",
        "home.disp.value": "Stage partout au Québec",
        "home.focus.label": "Focus",
        "home.focus.value": "Gameplay · IA · Réseaux",
        "home.profile.title": "Profil",
        "home.profile.text": "Étudiant motivé, encore junior, je veux apprendre davantage et m'investir dans des projets sérieux ou indépendants. Je recherche un stage dans le cadre de ma maîtrise à l'UQAC.",
        "home.recent.title": "Projets Récents",
        "home.recent.desc": "Un aperçu de mon travail. Découvrez la liste complète dans la section Projets.",

        // Projects Page
        "projects.title": "Mes Projets",
        "projects.desc": "Découvrez l'ensemble de mes projets, allant des jeux complets aux outils de développement.",
        "projects.filter.all": "Tous",
        "projects.filter.games": "Jeux",
        "projects.filter.tools": "Outils",
        "projects.filter.tests": "Tests techniques",

        // About Page
        "about.title": "À propos de moi",
        "about.lead": "Passionné par la création de jeux et le développement de systèmes interactifs.",
        "about.btn.cv.fr": "Télécharger CV (FR)",
        "about.btn.cv.en": "Télécharger CV (EN)",
        "about.btn.cv.visual": "CV Visuel",
        "about.btn.cv.latex": "CV Brut (LaTeX)",
        "about.cv.title": "Mon CV",
        "about.skills.title": "Compétences Techniques",
        "about.skills.section.title": "Mes Compétences",
        "about.skills.section.desc": "Technologies, langages et outils que je maîtrise.",
        "about.skills.prog.title": "Programmation & Moteurs",
        "about.skills.gameplay.title": "Gameplay & Systèmes",
        "about.skills.gameplay.desc": "Systèmes de combat<br>Behavior Trees & IA<br>Interfaces (UI)<br>Outils internes & Debug",
        "about.skills.tools.title": "Outils de Production",
        "about.skills.tools.desc": "Git & Perforce<br>Visual Studio & Rider<br>Jira & Trello<br>Méthodes Agiles",
        "about.exp.title": "Expérience & Formation",
        "about.timeline.title": "Parcours & Expériences",
        "about.timeline.desc": "Mon parcours académique et mes réalisations en équipe.",
        "about.timeline.1.date": "2025 - Présent",
        "about.timeline.1.title": "Maîtrise — Développement de jeux vidéo",
        "about.timeline.1.place": "UQAC (Université du Québec à Chicoutimi)",
        "about.timeline.1.desc": "Spécialisation en programmation Gameplay, IA, optimisation et création d'outils. Projets réalisés en équipe avec des étudiants artistes et designers.",
        "about.timeline.2.date": "Septembre 2024 - Avril 2025",
        "about.timeline.2.title": "Bi-diplomation — Développement de jeux vidéo",
        "about.timeline.2.place": "UQAC",
        "about.timeline.2.desc": "Programme d'échange étudiant approfondissant les concepts avancés du développement de jeux vidéo.",
        "about.timeline.3.date": "Juin 2024",
        "about.timeline.3.title": "Stage en développement",
        "about.timeline.3.place": "Stage de fin de licence",
        "about.timeline.3.desc": "Mise en pratique des compétences acquises lors de ma formation dans un environnement professionnel.",
        "about.timeline.4.date": "2022",
        "about.timeline.4.title": "Licence Informatique (Parcours A)",
        "about.timeline.4.place": "Université Savoie Mont Blanc",
        "about.timeline.4.desc": "Réalisation d'applications : Conception, Développement, Validation. Acquisition des bases solides en informatique fondamentale.",
        "about.ready.title": "Prêt à travailler ensemble ?",
        "about.ready.desc": "Je suis toujours ouvert aux nouvelles opportunités et aux discussions passionnantes autour du jeu vidéo.",
        "about.ready.btn": "Me contacter",

        // Contact Page
        "contact.title": "Contact",
        "contact.desc": "N'hésitez pas à me contacter pour toute opportunité de stage ou de collaboration.",
        "contact.btn.email": "M'envoyer un email",
        "contact.btn.linkedin": "Voir mon LinkedIn",
        "contact.page.title": "Me Contacter",
        "contact.page.lead": "Je suis ouvert aux opportunités, n'hésitez pas à m'écrire.",
        "contact.page.ready": "Prêt à discuter ?",
        "contact.page.desc": "Pour un stage, une collaboration ou juste échanger, vous pouvez utiliser les liens ci-contre.",

        // Footer
        "footer.text": "Fait avec passion.",
        "footer.updated": "Dernière mise à jour :",

        // Project Cards
        "card.btn.view": "Voir le projet",
        "card.category.game": "Jeu",
        "card.category.tool": "Outil",
        "card.category.test": "Test",
        "project.back": "← Retour aux projets",
        "proj.artest.title": "AR Test",
        "proj.artest.desc": "An augmented reality technical test using Unity and AR Foundation.",
,
        "proj.artest.title": "AR Test",
        "proj.artest.desc": "Un test technique en réalité augmentée avec Unity et AR Foundation.",

        "proj.moteurphysique.title": "Moteur Physique",
        "proj.moteurphysique.desc": "A 2D physics engine created from scratch in C++ with SDL2.",
,
        "proj.moteurphysique.title": "Moteur Physique",
        "proj.moteurphysique.desc": "Un moteur physique 2D créé de zéro en C++ avec SDL2.",

        "proj.bloodyescape.title": "BloodyEscape",
        "proj.bloodyescape.desc": "BloodyEscape is a 2D platformer where you must escape a dungeon filled with traps.",
,
        "proj.bloodyescape.title": "BloodyEscape",
        "proj.bloodyescape.desc": "BloodyEscape est un jeu de plateforme 2D où vous devez vous échapper d'un donjon rempli de pièges.",

        "proj.crittereats.title": "CritterEats",
        "proj.crittereats.desc": "CritterEats is a restaurant management game where you play as a chef for monsters.",
,
        "proj.crittereats.title": "CritterEats",
        "proj.crittereats.desc": "CritterEats est un jeu de gestion de restaurant où vous incarnez un cuisinier pour des monstres.",

        "proj.bedroomrumble.title": "Bedroom Rumble",
        "proj.bedroomrumble.desc": "Bedroom Rumble is a 2D fighting game where you play as toys in a child's bedroom.",
,
        "proj.bedroomrumble.title": "Bedroom Rumble",
        "proj.bedroomrumble.desc": "Bedroom Rumble est un jeu de combat en 2D où vous incarnez des jouets dans une chambre d'enfant.",

        "proj.onelaststake.title": "One Last Stake",
        "proj.onelaststake.desc": "OneLastTake is a card game inspired by the game of War in a rogue-lite.",
,
        "proj.onelaststake.title": "One Last Stake",
        "proj.onelaststake.desc": "OneLastTake est un jeu de carte inspiré du jeu de la bataille dans un rogue-lite.",

        "proj.apinodedrones.title": "API Node Drones",
        "proj.apinodedrones.desc": "A Node.js backend API for managing a fleet of drones.",
,
        "proj.apinodedrones.title": "API Node Drones",
        "proj.apinodedrones.desc": "Une API backend en Node.js pour la gestion d'une flotte de drones.",

        "proj.mytoolunreal.title": "My Tool Unreal",
        "proj.mytoolunreal.desc": "Unreal Engine plugin to easily generate procedural content.",
,
        "proj.mytoolunreal.title": "My Tool Unreal",
        "proj.mytoolunreal.desc": "Plugin Unreal Engine pour générer du contenu procédural facilement.",

        "proj.tropicmadness.title": "TropicMadness",
        "proj.tropicmadness.desc": "A thrilling adventure game in the wilderness with an advanced crafting system.",
,
        "proj.tropicmadness.title": "TropicMadness",
        "proj.tropicmadness.desc": "Un jeu d'aventure palpitant en pleine nature avec un système de crafting poussé.",


        // Common Project Info
        "project.role": "Rôle :",
        "project.team": "Équipe :",
        "project.context": "Contexte :",
        "project.features": "Mes contributions :",
        "project.btn.github": "Code Source (GitHub)",
        "project.btn.itch": "Jouer (Itch.io)"
    },
    en: {
        // Nav
        "nav.home": "Home",
        "nav.projects": "Projects",
        "nav.about": "About",
        "nav.contact": "Contact",

        // Home
        "home.eyebrow": "Gameplay & Systems",
        "home.title": "Crafting reliable and readable playable experiences.",
        "home.lead": "Video Game Developer, I use Unreal Engine to bring my game ideas to life. I love large-scale projects and learning more about the vast world of GameDev.",
        "home.btn.projects": "View my projects",
        "home.btn.about": "Learn more about me",
        "home.loc.label": "Location",
        "home.loc.value": "Chicoutimi (QC)",
        "home.disp.label": "Availability",
        "home.disp.value": "Internship anywhere in Quebec",
        "home.focus.label": "Focus",
        "home.focus.value": "Gameplay · AI · Networks",
        "home.profile.title": "Profile",
        "home.profile.text": "Highly motivated student, still a junior, I want to learn more and invest myself in serious or independent projects. I am looking for an internship as part of my Master's degree at UQAC.",
        "home.recent.title": "Recent Projects",
        "home.recent.desc": "A glimpse of my work. Discover the full list in the Projects section.",

        // Projects Page
        "projects.title": "My Projects",
        "projects.desc": "Discover all my projects, ranging from full games to development tools.",
        "projects.filter.all": "All",
        "projects.filter.games": "Games",
        "projects.filter.tools": "Tools",
        "projects.filter.tests": "Technical Tests",

        // About Page
        "about.title": "About Me",
        "about.lead": "Passionate about creating games and developing interactive systems.",
        "about.btn.cv.fr": "Download CV (FR)",
        "about.btn.cv.en": "Download CV (EN)",
        "about.btn.cv.visual": "Visual Resume",
        "about.btn.cv.latex": "Raw Resume (LaTeX)",
        "about.cv.title": "My Resume",
        "about.skills.title": "Technical Skills",
        "about.skills.section.title": "My Skills",
        "about.skills.section.desc": "Technologies, languages and tools I master.",
        "about.skills.prog.title": "Programming & Engines",
        "about.skills.gameplay.title": "Gameplay & Systems",
        "about.skills.gameplay.desc": "Combat systems<br>Behavior Trees & AI<br>User Interfaces (UI)<br>Internal Tools & Debugging",
        "about.skills.tools.title": "Production Tools",
        "about.skills.tools.desc": "Git & Perforce<br>Visual Studio & Rider<br>Jira & Trello<br>Agile Methods",
        "about.exp.title": "Experience & Education",
        "about.timeline.title": "Background & Experience",
        "about.timeline.desc": "My academic background and team achievements.",
        "about.timeline.1.date": "2025 - Present",
        "about.timeline.1.title": "Master's — Video Game Development",
        "about.timeline.1.place": "UQAC (University of Quebec at Chicoutimi)",
        "about.timeline.1.desc": "Specialization in Gameplay programming, AI, optimization and tool creation. Projects carried out in teams with art and design students.",
        "about.timeline.2.date": "September 2024 - April 2025",
        "about.timeline.2.title": "Dual Degree — Video Game Development",
        "about.timeline.2.place": "UQAC",
        "about.timeline.2.desc": "Student exchange program deepening advanced concepts of video game development.",
        "about.timeline.3.date": "June 2024",
        "about.timeline.3.title": "Development Internship",
        "about.timeline.3.place": "End of Bachelor's Internship",
        "about.timeline.3.desc": "Applying skills acquired during my training in a professional environment.",
        "about.timeline.4.date": "2022",
        "about.timeline.4.title": "Bachelor's in Computer Science (Path A)",
        "about.timeline.4.place": "Savoie Mont Blanc University",
        "about.timeline.4.desc": "Application creation: Design, Development, Validation. Acquisition of solid fundamentals in computer science.",
        "about.ready.title": "Ready to work together?",
        "about.ready.desc": "I am always open to new opportunities and exciting discussions about video games.",
        "about.ready.btn": "Contact me",

        // Contact Page
        "contact.title": "Contact",
        "contact.desc": "Feel free to reach out for any internship or collaboration opportunities.",
        "contact.btn.email": "Send me an email",
        "contact.btn.linkedin": "View my LinkedIn",
        "contact.page.title": "Contact Me",
        "contact.page.lead": "I am open to opportunities, feel free to write me.",
        "contact.page.ready": "Ready to chat?",
        "contact.page.desc": "For an internship, a collaboration or just to chat, you can use the links provided.",

        // Footer
        "footer.text": "Made with passion.",
        "footer.updated": "Last updated:",

        // Project Cards
        "card.btn.view": "View project",
        "card.category.game": "Game",
        "card.category.tool": "Tool",
        "card.category.test": "Test",
        "project.back": "← Back to projects",
        "proj.artest.title": "AR Test",
        "proj.artest.desc": "An augmented reality technical test using Unity and AR Foundation.",
,
        "proj.moteurphysique.title": "Moteur Physique",
        "proj.moteurphysique.desc": "A 2D physics engine created from scratch in C++ with SDL2.",
,
        "proj.bloodyescape.title": "BloodyEscape",
        "proj.bloodyescape.desc": "BloodyEscape is a 2D platformer where you must escape a dungeon filled with traps.",
,
        "proj.crittereats.title": "CritterEats",
        "proj.crittereats.desc": "CritterEats is a restaurant management game where you play as a chef for monsters.",
,
        "proj.bedroomrumble.title": "Bedroom Rumble",
        "proj.bedroomrumble.desc": "Bedroom Rumble is a 2D fighting game where you play as toys in a child's bedroom.",
,
        "proj.onelaststake.title": "One Last Stake",
        "proj.onelaststake.desc": "OneLastTake is a card game inspired by the game of War in a rogue-lite.",
,
        "proj.apinodedrones.title": "API Node Drones",
        "proj.apinodedrones.desc": "A Node.js backend API for managing a fleet of drones.",
,
        "proj.mytoolunreal.title": "My Tool Unreal",
        "proj.mytoolunreal.desc": "Unreal Engine plugin to easily generate procedural content.",
,
        "proj.tropicmadness.title": "TropicMadness",
        "proj.tropicmadness.desc": "A thrilling adventure game in the wilderness with an advanced crafting system.",
,

        // Common Project Info
        "project.role": "Role:",
        "project.team": "Team:",
        "project.context": "Context:",
        "project.features": "My contributions:",
        "project.btn.github": "Source Code (GitHub)",
        "project.btn.itch": "Play (Itch.io)"
    }
};

document.addEventListener("languageChanged", (e) => {
    const lang = e.detail.lang;
    document.querySelectorAll("[data-i18n]").forEach(el => {
        const key = el.getAttribute("data-i18n");
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });
});
